// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type NewTopicInput struct {
	Topics string `json:"topics"`
}

type Query struct {
}

type RegisterInput struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type StudyNote struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type Topic struct {
	ID     string `json:"id"`
	Topics string `json:"topics"`
}

type UpdateTopicInput struct {
	Topics string `json:"topics"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
